[package]
name = "data-exporter-uninstaller"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "uninstaller"
path = "src/main.rs"

[dependencies]
# GUI Framework
native-windows-gui = { workspace = true }
native-windows-derive = { workspace = true }

# Error Handling
anyhow = { workspace = true }
