[package]
name = "data-exporter-installer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "installer"
path = "src/main.rs"

[dependencies]
# Common library
common = { workspace = true }

# GUI Framework
native-windows-gui = { workspace = true }
native-windows-derive = { workspace = true }

# Error Handling
anyhow = { workspace = true }

# Windows API
windows = { workspace = true }

[build-dependencies]
winres = "0.1"
